# 				Configuration for 'Build My Text'
#
# 						By CraterHater
#		Please report any issues, suggestions or questions. 
#
#		Contact; 
#		CraterCMD@outlook.com
#			
#
#		Configuration allows for various changes to be made to internal
#		systems of this plugin. Please do not touch any settings you are
#		unsure about. It may cause the plugin to stop working the way you
#		intend it to. Please keep the '' around text. 
#
#		
#		This configuration will automatically add new entries when updating
#		to newer versions. It will not overwrite or change entries. This means
#		some entries may need to be deleted if entries are changed. Please read
#		update changelogs carefully when updating from Spigot.
#
#		


# 		Administrative Settings
show_startup_message: true

# The command that is used to control the plugin. You can change it to whatever you wish.
main_command: 'text'

# Alternatives you can use instead of the main command
command_aliases:
- 't'

# What permission users must have to access all commands. Give them the permission specified below + '.*' to give them access to all commands. Operators always have access to all commands.
main_permission: 'textBuilder'